import { afterEach, beforeEach, expect, it } from 'vitest';
import request from 'supertest';
import { createTestServer, loginAgent } from '../helpers';
import { offlinePacketError } from '../../src/shared/offlineAir';
import { verifyOfflinePacketProof } from '../../src/server/offlineAir';
let server: Awaited<ReturnType<typeof createTestServer>>;
beforeEach(async () => { server = await createTestServer(); });
afterEach(() => server.close());
it('requires authentication and prepares ordered confirmed text with authoritative versions', async () => {
  const bulletin = server.db.listCollection('bulletins')[0];
  expect((await request(server.app).get(`/api/v1/air-offline/packet/${bulletin.id}`)).status).toBe(401);
  const admin = await loginAgent(server.app, 'admin@akhbar.tv');
  const response = await admin.get(`/api/v1/air-offline/packet/${bulletin.id}`);
  expect(response.status).toBe(200);
  expect(response.headers['cache-control']).toBe('no-store');
  const packet = response.body.packet;
  expect(offlinePacketError(packet)).toBeNull();
  expect(packet.dbId).toBe(server.db.dbId);
  expect(packet.show.id).toBe(bulletin.id);
  expect(packet.canEdit).toBe(false);
  expect(verifyOfflinePacketProof(server.db, packet.userId, packet)).toBe(true);
  expect(verifyOfflinePacketProof(server.db, 'another-user', packet)).toBe(false);
  expect(verifyOfflinePacketProof(server.db, packet.userId, { ...packet, dbId: 'another-database' })).toBe(false);
  expect(verifyOfflinePacketProof(server.db, packet.userId, { ...packet, show: { ...packet.show, id: 'another-show' } })).toBe(false);
  expect(verifyOfflinePacketProof(server.db, packet.userId, packet, Date.parse(packet.preparedAt) + 31 * 86400000)).toBe(false);
  expect(packet.baseRows.find((row: any) => row.id === bulletin.id).v).toBe(bulletin.v);
  const stories = server.db.listCollection('bulletinStories').map(row => row.d).filter((story: any) => story.bulletinId === bulletin.id && !story.killed && !story.floated && !story.deletedAt).sort((a: any, b: any) => a.rank - b.rank);
  expect(packet.show.segments.map((segment: any) => segment.id)).toEqual(stories.map((story: any) => story.id));
  for (const segment of packet.show.segments) if (!segment.approved) expect(segment.script).toBe('');
  expect((await admin.get('/api/v1/air-offline/packet/missing')).status).toBe(404);
});
