import {
  User,
  Category, Story,
  NewsSource,
  ProgramType,
  Program,
  Episode,
  Guest,
  EditorialTask,
  MediaFile,
  BreakingNews,
  AppNotification,
  ActivityLog,
  AuditLog,
  SystemSettings,
  NewsItem,
  ProgramEvaluation,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    fullName: 'أحمد المنصوري',
    fullNameEn: 'Ahmed Al-Mansouri',
    email: 'admin@akhbar.tv',
    phone: '+971 50 123 4567',
    role: 'SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'المدير العام لشبكة الأخبار',
    department: 'الإدارة العامة والتحرير',
    isActive: true,
    createdAt: '2025-01-01T08:00:00Z',
  },
  {
    id: 'usr-2',
    fullName: 'سارة عبد العزيز',
    fullNameEn: 'Sarah Abdulaziz',
    email: 'editor@akhbar.tv',
    phone: '+966 54 987 6543',
    role: 'EDITOR',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'مديرة التحرير ورئيسة غرفة الأخبار',
    department: 'غرفة الأخبار',
    isActive: true,
    createdAt: '2025-01-10T09:30:00Z',
  },
  {
    id: 'usr-3',
    fullName: 'طارق الهاشمي',
    fullNameEn: 'Tariq Al-Hashemi',
    email: 'journalist@akhbar.tv',
    phone: '+962 79 555 1234',
    role: 'JOURNALIST',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'صحفي ومحرر شؤون دولية',
    department: 'القسم الدولي',
    isActive: true,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'usr-4',
    fullName: 'ريم القحطاني',
    fullNameEn: 'Reem Al-Qahtani',
    email: 'producer@akhbar.tv',
    phone: '+966 50 444 8888',
    role: 'PRODUCER',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'منتجة برامج أولى',
    department: 'الإنتاج والبرامج',
    isActive: true,
    createdAt: '2025-02-01T11:00:00Z',
  },
  {
    id: 'usr-5',
    fullName: 'فيصل العتيبي',
    fullNameEn: 'Faisal Al-Otaibi',
    email: 'presenter@akhbar.tv',
    phone: '+966 55 777 9999',
    role: 'PRESENTER',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'مذيع ومقدم برامج رئيسي',
    department: 'المذيعين والتقديم',
    isActive: true,
    createdAt: '2025-02-10T12:00:00Z',
  },
  {
    id: 'usr-6',
    fullName: 'ليلى النجار',
    fullNameEn: 'Layla Al-Najjar',
    email: 'reporter@akhbar.tv',
    phone: '+970 59 888 2222',
    role: 'REPORTER',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'مراسلة ميدانية',
    department: 'المراسلين الميدانيين',
    isActive: true,
    createdAt: '2025-02-15T08:30:00Z',
  },
  {
    id: 'usr-7',
    fullName: 'عمر الدوسري',
    fullNameEn: 'Omar Al-Dossari',
    email: 'media@akhbar.tv',
    phone: '+966 53 111 4444',
    role: 'MEDIA',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    jobTitle: 'مسؤول المونتاج والمكتبة الرقمية',
    department: 'الوسائط والمكتبة',
    isActive: true,
    createdAt: '2025-02-20T09:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', nameAr: 'سياسة', nameEn: 'Politics', slug: 'politics', color: '#dc2626', orderIndex: 1 },
  { id: 'cat-2', nameAr: 'اقتصاد', nameEn: 'Economy', slug: 'economy', color: '#16a34a', orderIndex: 2 },
  { id: 'cat-3', nameAr: 'محلي', nameEn: 'Local', slug: 'local', color: '#2563eb', orderIndex: 3 },
  { id: 'cat-4', nameAr: 'دولي', nameEn: 'International', slug: 'international', color: '#7c3aed', orderIndex: 4 },
  { id: 'cat-5', nameAr: 'تكنولوجيا', nameEn: 'Technology', slug: 'tech', color: '#0891b2', orderIndex: 5 },
  { id: 'cat-6', nameAr: 'رياضة', nameEn: 'Sports', slug: 'sports', color: '#ea580c', orderIndex: 6 },
  { id: 'cat-7', nameAr: 'ثقافة ومجتمع', nameEn: 'Culture & Society', slug: 'culture', color: '#d97706', orderIndex: 7 },
];

export const INITIAL_SOURCES: NewsSource[] = [
  { id: 'src-1', name: 'المراسل الميداني لشبكة الأخبار', type: 'REPORTER', reliabilityScore: 5, contactInfo: 'ليلى النجار - القدس', notes: 'تغطيات حصرية وموثوقة من الميدان' },
  { id: 'src-2', name: 'وكالة الأنباء الرسمية (واس)', type: 'NEWS_AGENCY', reliabilityScore: 5, contactInfo: 'spa.gov.sa', notes: 'البيانات والأوامر الملكية والقرارات الحكومية' },
  { id: 'src-3', name: 'وكالة رويترز العالمية', type: 'NEWS_AGENCY', reliabilityScore: 5, contactInfo: 'reuters.com', notes: 'سلك الأنباء الدولي والأسواق العالمية' },
  { id: 'src-4', name: 'بيان رسمي - وزارة الخارجية', type: 'OFFICIAL_STATEMENT', reliabilityScore: 5, notes: 'المواقف الدبلوماسية الرسمية' },
  { id: 'src-5', name: 'مقابلة خاصة واستقصائية', type: 'INTERVIEW', reliabilityScore: 4, notes: 'لقاءات حصرية لبرامج القناة' },
  { id: 'src-6', name: 'مصادر مطلعة وموثوقة', type: 'SPECIAL_SOURCE', reliabilityScore: 4, notes: 'تسريبات ومصادر دبلوماسية خاصة' },
];

export const INITIAL_PROGRAM_TYPES: ProgramType[] = [
  { id: 'pt-1', nameAr: 'نشرة إخبارية', description: 'نشرات الأخبار الموجزة والمفصلة على مدار الساعة' },
  { id: 'pt-2', nameAr: 'برنامج حواري سياسي', description: 'نقاشات معمقة مع صناع القرار والمحللين السياسيين' },
  { id: 'pt-3', nameAr: 'برنامج اقتصادي', description: 'تحليلات أسواق الطاقة، البورصات والتمويل والاستثمار' },
  { id: 'pt-4', nameAr: 'برنامج صباحي', description: 'تغطيات مجتمعية، صحافة يومية وموضوعات خفيفة' },
  { id: 'pt-5', nameAr: 'تغطية خاصة ومفتوحة', description: 'بث استثنائي لمواكبة الأحداث العاجلة والقمم الدولية' },
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'gst-1',
    fullName: 'د. خالد بن صالح الشمري',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    organization: 'مركز الدراسات الاستراتيجية والدولية',
    jobTitle: 'أستاذ العلوم السياسية والعلاقات الدولية',
    specialty: 'السياسات الإقليمية والأمن القومي',
    phone: '+966 50 111 2233',
    email: 'k.alshammari@strategy-center.org',
    rating: 5,
    totalAppearances: 8,
    notes: 'متحدث لبق، يلتزم بالوقت المحدد، يحظى بمتابعة جماهيرية عالية.',
    createdAt: '2025-01-05T10:00:00Z',
  },
  {
    id: 'gst-2',
    fullName: 'نورة بنت راشد الكواري',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&q=80',
    organization: 'المعهد العربي لأسواق المال والطاقة',
    jobTitle: 'كبيرة مستشاري الاقتصاد الكلي',
    specialty: 'أسواق النفط، أوبك+ والاستثمار الأخضر',
    phone: '+974 55 888 7766',
    email: 'n.alkuwari@energy-inst.org',
    rating: 5,
    totalAppearances: 5,
    notes: 'ممتازة في الرسوم البيانية وقراءة حركة أسعار النفط العالمية.',
    createdAt: '2025-01-12T14:00:00Z',
  },
  {
    id: 'gst-3',
    fullName: 'م. مروان بن زياد التميمي',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    organization: 'الهيئة الوطنية للذكاء الاصطناعي والأمن السيبراني',
    jobTitle: 'خبير التحول الرقمي والتقنيات الناشئة',
    specialty: 'الذكاء الاصطناعي التوليدي، حوكمة البيانات والتقنية',
    phone: '+966 54 333 9988',
    email: 'm.tamimi@cyber-council.gov',
    rating: 4,
    totalAppearances: 3,
    notes: 'يفضل الشرح التوضيحي المبسط للجمهور غير المتخصص.',
    createdAt: '2025-01-20T09:00:00Z',
  },
  {
    id: 'gst-4',
    fullName: 'د. سامي يوسف البشير',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    organization: 'منظمة الصحة العالمية - إقليم الشرق المتوسط',
    jobTitle: 'خبير الأوبئة والسياسات الصحية',
    specialty: 'الأمن الصحي الوقائي وبروتوكولات الطوارئ',
    phone: '+20 10 2222 3344',
    email: 's.albashir@who-emro.org',
    rating: 4,
    totalAppearances: 2,
    notes: 'جاهز للمداخلات عبر الأقمار الصناعية وSkype.',
    createdAt: '2025-02-05T15:30:00Z',
  },
];

export const INITIAL_STORIES: Story[] = [
  {
    id: 's-100',
    title: 'الانتخابات البرلمانية 2026',
    description: 'تغطية شاملة للانتخابات البرلمانية لعام 2026 بما في ذلك التحضيرات، الحملات الانتخابية، والنتائج.',
    slug: 'parliament-elections-2026',
    categoryId: 'c-1',
    categoryName: 'سياسة',
    priority: 'HIGH',
    status: 'ACTIVE',
    keywords: ['انتخابات', 'برلمان', 'سياسة'],
    startedAt: '2026-05-01T00:00:00Z',
    createdBy: 'u-1',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-05-01T00:00:00Z'
  },
  {
    id: 's-101',
    title: 'قمة المناخ الإقليمية',
    description: 'متابعة حية ومباشرة لفعاليات قمة المناخ الإقليمية المنعقدة في العاصمة.',
    slug: 'regional-climate-summit',
    categoryId: 'c-1',
    priority: 'NORMAL',
    status: 'ACTIVE',
    keywords: ['مناخ', 'قمة', 'بيئة'],
    startedAt: '2026-09-10T00:00:00Z',
    createdBy: 'u-2',
    createdAt: '2026-09-10T00:00:00Z',
    updatedAt: '2026-09-12T00:00:00Z'
  }
];

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: 'nws-1',
    storyId: 's-100',
    title: 'انطلاق أعمال القمة الاقتصادية العربية لمناقشة شراكات الاستثمار المستدام وسلاسل الإمداد',
    shortTitle: 'انطلاق القمة الاقتصادية لمناقشة الاستثمار المستدام',
    slug: 'arab-economic-summit-sustainable-investment-2026',
    summary: 'انطلقت اليوم أعمال القمة بمشاركة وزراء المالية والاقتصاد لبحث توسيع مشاريع الطاقة النظيفة وتيسير التبادل التجاري البيني ودعم الابتكار التقني.',
    content: `<h2>محاور القمة الاقتصادية الكبرى</h2>
<p>افتتحت في العاصمة اليوم أعمال القمة الاقتصادية وسط حضور رفيع المستوى من ممثلي أكثر من 20 دولة ومنظمة دولية، حيث تركز جلسات اليوم الأول على التحديات الراهنة في سلاسل الإمداد العالمية وفرص الاستثمار المشترك في البنية التحتية الخضراء.</p>
<p>وأكد رئيس الجلسة الافتتاحية أن التكامل الاقتصادي العربي لم يعد خياراً ترفيهياً بل ضرورة حتمية لمواجهة التقلبات في أسواق المال وأسعار الطاقة، مشيراً إلى أن المبادرات المطروحة تتضمن إنشاء صندوق استثماري مشترك برأسمال أولي واعد.</p>
<h3>جلسات العمل والاتفاقيات المزمع توقيعها:</h3>
<ul>
<li><strong>مشروع الربط الكهربائي الإقليمي:</strong> توسيع شبكات النقل لتبادل الفائض من الطاقة المتجددة.</li>
<li><strong>المنصة الرقمية للجمارك الموحدة:</strong> تقليص زمن التخليص الجمركي بين المنافذ الحدودية.</li>
<li><strong>دعم الشركات الناشئة والذكاء الاصطناعي:</strong> إطلاق مسرعات أعمال عابرة للحدود بتمويل مشترك.</li>
</ul>
<blockquote>"هدفنا الانتقال من مرحلة التوصيات إلى المشاريع التنفيذية ذات العائد المباشر على المواطن واقتصادات المنطقة."</blockquote>
<p>ومن المتوقع أن تصدر القمة في ختام أعمالها بياناً ختامياً مفصلاً يتضمن جدولاً زمنياً ملزماً لتنفيذ بنود الاتفاقيات الموقعة.</p>`,
    mainImageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    sourceId: 'src-2',
    sourceName: 'وكالة الأنباء الرسمية (واس)',
    categoryId: 'cat-2',
    categoryName: 'اقتصاد',
    authorId: 'usr-3',
    authorName: 'طارق الهاشمي',
    editorId: 'usr-2',
    editorName: 'سارة عبد العزيز',
    priority: 'HIGH',
    status: 'PUBLISHED',
    keywords: ['القمة الاقتصادية', 'الاستثمار المستدام', 'سلاسل الإمداد', 'الطاقة المتجددة', 'الربط الكهربائي'],
    locationName: 'الرياض',
    eventDate: '2026-09-13T08:00:00Z',
    publishDate: '2026-09-13T09:30:00Z',
    isBreaking: false,
    internalNotes: 'تم التنسيق مع المراسل لإجراء لقاء جانبي مع وزير الاقتصاد عند الساعة الواحدة ظهراً.',
    viewsCount: 14200,
    workflowLogs: [
      {
        id: 'log-1',
        newsId: 'nws-1',
        fromStatus: 'DRAFT',
        toStatus: 'NEEDS_REVISION',
        changedBy: { id: 'usr-3', name: 'طارق الهاشمي', role: 'JOURNALIST' },
        comment: 'تم الانتهاء من مسودة الخبر وتدقيق الاقتباسات الرسمية.',
        timestamp: '2026-09-13T08:45:00Z',
      },
      {
        id: 'log-2',
        newsId: 'nws-1',
        fromStatus: 'NEEDS_REVISION',
        toStatus: 'APPROVED',
        changedBy: { id: 'usr-2', name: 'سارة عبد العزيز', role: 'EDITOR' },
        comment: 'تمت المراجعة والاعتماد التحريري، المحتوى مكتمل ومدعوم بصور عالية الدقة.',
        timestamp: '2026-09-13T09:15:00Z',
      },
      {
        id: 'log-3',
        newsId: 'nws-1',
        fromStatus: 'APPROVED',
        toStatus: 'PUBLISHED',
        changedBy: { id: 'usr-2', name: 'سارة عبد العزيز', role: 'EDITOR' },
        comment: 'نشر فوري عبر شريط الموقع والبث الإخباري المتزامن.',
        timestamp: '2026-09-13T09:30:00Z',
      },
    ],
    createdAt: '2026-09-13T08:15:00Z',
    updatedAt: '2026-09-13T09:30:00Z',
  },
  {
    id: 'nws-2',
    storyId: 's-101',
    title: 'عاجل: توقيع اتفاقية استراتيجية لتأسيس أكبر مجمع إقليمي للحوسبة السحابية ومراكز بيانات الذكاء الاصطناعي',
    shortTitle: 'توقيع اتفاقية إنشاء مجمع الذكاء الاصطناعي ومراكز البيانات',
    slug: 'strategic-cloud-ai-datacenter-agreement',
    summary: 'اتفاقية بقيمة 8 مليارات دولار لتشييد مراكز بيانات فائقة القدرة تعتمد بنسبة 100% على الطاقة المتجددة وتخدم كبرى نماذج المعالجة المتقدمة.',
    content: `<h2>قفزة تاريخية في البنية التحتية للذكاء الاصطناعي</h2>
<p>شهد اليوم توقيع مذكرة تفاهم استثمارية ضخمة تهدف إلى بناء شبكة مراكز بيانات سيادية متطورة، بطاقة استيعابية تتجاوز 500 ميجاواط، لتلبية الطلب المتسارع على معالجة النماذج التوليدية الضخمة والحوسبة الكمية.</p>
<p>وحسب البيان، سيوفر المجمع الجديد آلاف الوظائف النوعية للمهندسين والمختصين في علوم البيانات والأمن السيبراني، مع استقطاب كبرى شركات التكنولوجيا العالمية لإنشاء مقارها الإقليمية.</p>`,
    mainImageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    sourceId: 'src-4',
    sourceName: 'بيان رسمي - وزارة الخارجية',
    categoryId: 'cat-5',
    categoryName: 'تكنولوجيا',
    authorId: 'usr-3',
    authorName: 'طارق الهاشمي',
    editorId: 'usr-2',
    editorName: 'سارة عبد العزيز',
    priority: 'URGENT',
    status: 'PUBLISHED',
    keywords: ['الذكاء الاصطناعي', 'مراكز البيانات', 'الحوسبة السحابية', 'استثمار تقني', 'طاقة نظيفة'],
    locationName: 'دبي / الرياض',
    eventDate: '2026-09-13T10:00:00Z',
    publishDate: '2026-09-13T10:15:00Z',
    isBreaking: true,
    breakingUntil: '2026-09-13T16:00:00Z',
    viewsCount: 28900,
    workflowLogs: [
      {
        id: 'log-21',
        newsId: 'nws-2',
        fromStatus: 'DRAFT',
        toStatus: 'APPROVED',
        changedBy: { id: 'usr-2', name: 'سارة عبد العزيز', role: 'EDITOR' },
        comment: 'موافقة عاجلة واستثنائية نظراً لأهمية الاتفاقية وورود البيان المباشر.',
        timestamp: '2026-09-13T10:10:00Z',
      },
      {
        id: 'log-22',
        newsId: 'nws-2',
        fromStatus: 'APPROVED',
        toStatus: 'PUBLISHED',
        changedBy: { id: 'usr-2', name: 'سارة عبد العزيز', role: 'EDITOR' },
        comment: 'نشر عاجل مع رفع الأولوية للقصوى وتفعيل شريط العاجل.',
        timestamp: '2026-09-13T10:15:00Z',
      },
    ],
    createdAt: '2026-09-13T10:05:00Z',
    updatedAt: '2026-09-13T10:15:00Z',
  },
  {
    id: 'nws-3',
    title: 'تقرير ميداني: استكمال التجهيزات اللوجستية لافتتاح خط المترو الجديد وتوقعات بخدمة مليون راكب يومياً',
    shortTitle: 'استكمال تجهيزات خط المترو الجديد',
    slug: 'metro-line-logistics-launch-report',
    summary: 'جولة ميدانية مع فريق المهندسين ترصد أحدث قطارات الجيل الخامس ذاتية القيادة والمحطات الصديقة للبيئة.',
    content: `<p>ترصد كاميرا شبكتنا اللمسات الأخيرة قبيل التدشين الرسمي لأحدث شبكات النقل الحضري الذكي في المنطقة، والتي تمثل نقلة نوعية في منظومة النقل العام والتنقل المستدام.</p>`,
    mainImageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
    sourceId: 'src-1',
    sourceName: 'المراسل الميداني لشبكة الأخبار',
    categoryId: 'cat-3',
    categoryName: 'محلي',
    authorId: 'usr-6',
    authorName: 'ليلى النجار',
    editorId: 'usr-2',
    editorName: 'سارة عبد العزيز',
    priority: 'NORMAL',
    status: 'NEEDS_REVISION',
    keywords: ['المترو', 'النقل العام', 'مشاريع البنية التحتية', 'تلوث الهواء'],
    locationName: 'القاهرة / الرياض',
    eventDate: '2026-09-13T11:00:00Z',
    isBreaking: false,
    viewsCount: 350,
    workflowLogs: [
      {
        id: 'log-31',
        newsId: 'nws-3',
        fromStatus: 'DRAFT',
        toStatus: 'NEEDS_REVISION',
        changedBy: { id: 'usr-6', name: 'ليلى النجار', role: 'REPORTER' },
        comment: 'تم رفع التقرير الميداني مع لقطات فيديو للمحطات الرئيسية.',
        timestamp: '2026-09-13T11:15:00Z',
      },
    ],
    createdAt: '2026-09-13T10:45:00Z',
    updatedAt: '2026-09-13T11:15:00Z',
  },
  {
    id: 'nws-4',
    title: 'تحليل سياسي: توازنات القوى في المفاوضات الدولية حول معاهدة المناخ والأمن الغذائي',
    shortTitle: 'توازنات المفاوضات الدولية حول معاهدة المناخ',
    slug: 'international-climate-treaty-analysis',
    summary: 'قراءة استراتيجية في التباينات بين الدول الصناعية والدول النامية بشأن آليات التعويض وحصص الانبعاثات الكربونية.',
    content: `<p>مع اقتراب الجولة الحاسمة من المفاوضات، تبرز مسألة العدالة المناخية ونقل التكنولوجيا كعقدة رئيسة بين الوفود المشاركة.</p>`,
    mainImageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    sourceId: 'src-3',
    sourceName: 'وكالة رويترز العالمية',
    categoryId: 'cat-1',
    categoryName: 'سياسة',
    authorId: 'usr-3',
    authorName: 'طارق الهاشمي',
    priority: 'NORMAL',
    status: 'NEEDS_REVISION',
    keywords: ['المناخ', 'المفاوضات الدولية', 'الأمن الغذائي', 'الانبعاثات'],
    locationName: 'جنيف',
    eventDate: '2026-09-12T16:00:00Z',
    isBreaking: false,
    viewsCount: 110,
    workflowLogs: [
      {
        id: 'log-41',
        newsId: 'nws-4',
        fromStatus: 'DRAFT',
        toStatus: 'NEEDS_REVISION',
        changedBy: { id: 'usr-3', name: 'طارق الهاشمي', role: 'JOURNALIST' },
        comment: 'مرفق للتحرير.',
        timestamp: '2026-09-12T17:00:00Z',
      },
      {
        id: 'log-42',
        newsId: 'nws-4',
        fromStatus: 'NEEDS_REVISION',
        toStatus: 'NEEDS_REVISION',
        changedBy: { id: 'usr-2', name: 'سارة عبد العزيز', role: 'EDITOR' },
        comment: 'يرجى تدقيق أرقام صندوق المناخ الأخضر وإضافة وجهة نظر الدول النامية بتوازن أكبر.',
        timestamp: '2026-09-12T18:30:00Z',
      },
    ],
    createdAt: '2026-09-12T16:30:00Z',
    updatedAt: '2026-09-12T18:30:00Z',
  },
  {
    id: 'nws-5',
    title: 'مسودة: بطولات التنس العالمية تعلن اعتماد تقنية التحكيم الذكي بالكامل وإلغاء حكام الخطوط',
    shortTitle: 'اعتماد التحكيم الذكي في بطولات التنس',
    slug: 'tennis-championships-full-ai-referee-draft',
    summary: 'مسودة قيد التحرير حول القرار التاريخي للاتحاد الدولي للعبة.',
    content: `<p>يجري تحرير الخبر فور صدور المؤتمر الصحفي الرسمي في لندن بعد قليل.</p>`,
    mainImageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
    sourceId: 'src-3',
    sourceName: 'وكالة رويترز العالمية',
    categoryId: 'cat-6',
    categoryName: 'رياضة',
    authorId: 'usr-3',
    authorName: 'طارق الهاشمي',
    priority: 'LOW',
    status: 'DRAFT',
    keywords: ['التنس', 'التحكيم الذكي', 'رياضة عالمية'],
    locationName: 'لندن',
    eventDate: '2026-09-13T12:00:00Z',
    isBreaking: false,
    viewsCount: 15,
    workflowLogs: [],
    createdAt: '2026-09-13T11:45:00Z',
    updatedAt: '2026-09-13T11:45:00Z',
  },
];

export const INITIAL_BREAKING_NEWS: BreakingNews[] = [
  {
    id: 'brk-1',
    newsId: 'nws-2',
    title: 'عاجل: توقيع اتفاقية استراتيجية كبرى لتأسيس أكبر مجمع إقليمي للحوسبة السحابية والذكاء الاصطناعي بقيمة 8 مليارات دولار',
    priority: 'CRITICAL',
    isActive: true,
    startedAt: '2026-09-13T10:15:00Z',
    expiresAt: '2026-09-13T18:00:00Z',
    createdBy: 'سارة عبد العزيز',
  },
  {
    id: 'brk-2',
    title: 'الأرصاد تطلق تحذيراً من عواصف رملية ورياح نشطة على الطرق السريعة خلال الساعات الأربع القادمة',
    priority: 'HIGH',
    isActive: true,
    startedAt: '2026-09-13T11:00:00Z',
    expiresAt: '2026-09-13T15:00:00Z',
    createdBy: 'أحمد المنصوري',
  },
];

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prg-1',
    name: 'المشهد السياسي',
    shortName: 'المشهد',
    description: 'برنامج حواري استراتيجي يحلل أبرز التطورات والملفات الإقليمية والدولية الساخنة مع كبار الخبراء وصناع القرار.',
    coverImageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80',
    typeId: 'pt-2',
    typeName: 'برنامج حواري سياسي',
    presenterId: 'usr-5',
    presenterName: 'فيصل العتيبي',
    producerId: 'usr-4',
    producerName: 'ريم القحطاني',
    teamMembers: ['فيصل العتيبي', 'ريم القحطاني', 'عمر الدوسري', 'هاني رضوان (مخرج)'],
    broadcastDays: ['الأحد', 'الثلاثاء', 'الخميس'],
    broadcastTime: '21:00',
    durationMinutes: 50,
    channelName: 'القناة الإخبارية الأولى',
    studioName: 'استوديو الأخبار الرئيسي (A1)',
    status: 'ACTIVE',
    notes: 'البث المباشر بتقنية 4K مع استخدام تقنيات الشاشات التفاعلية والغرافيك المعزز (AR).',
    episodesCount: 142,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prg-2',
    name: 'عين على الاقتصاد',
    shortName: 'عين الاقتصاد',
    description: 'رصد شامل لأداء الأسواق المالية، أسعار النفط، مؤشرات التضخم وفرص ريادة الأعمال والاستثمار.',
    coverImageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    typeId: 'pt-3',
    typeName: 'برنامج اقتصادي',
    presenterId: 'usr-5',
    presenterName: 'فيصل العتيبي',
    producerId: 'usr-4',
    producerName: 'ريم القحطاني',
    teamMembers: ['فيصل العتيبي', 'طارق الهاشمي', 'نور الشيخ'],
    broadcastDays: ['الإثنين', 'الأربعاء'],
    broadcastTime: '19:00',
    durationMinutes: 45,
    channelName: 'القناة الإخبارية الأولى',
    studioName: 'استوديو الاقتصاد والأسواق (B2)',
    status: 'ACTIVE',
    notes: 'ربط حي مع شاشات أسواق المال في الرياض ودبي ولندن.',
    episodesCount: 88,
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'prg-3',
    name: 'نشرة الأخبار الرئيسة (التاسعة)',
    shortName: 'نشرة التاسعة',
    description: 'الحصيلة الإخبارية اليومية الشاملة لأهم أحداث المنطقة والعالم، مع شبكة المراسلين والتقارير الميدانية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=800&q=80',
    typeId: 'pt-1',
    typeName: 'نشرة إخبارية',
    presenterId: 'usr-5',
    presenterName: 'فيصل العتيبي',
    producerId: 'usr-2',
    producerName: 'سارة عبد العزيز',
    teamMembers: ['سارة عبد العزيز', 'فيصل العتيبي', 'ليلى النجار', 'عمر الدوسري'],
    broadcastDays: ['يومياً'],
    broadcastTime: '21:00',
    durationMinutes: 60,
    channelName: 'القناة الإخبارية الأولى',
    studioName: 'استوديو الأخبار الرئيسي (A1)',
    status: 'ACTIVE',
    notes: 'أهم موعد إخباري في خريطة القناة البرامجية.',
    episodesCount: 730,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prg-4',
    name: 'صباح الصحافة',
    shortName: 'صباح الصحافة',
    description: 'قراءة يومية في عناوين الصحف والمقالات البارزة ومنصات التواصل الاجتماعي مع نخبة من الكتاب والإعلاميين.',
    coverImageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80',
    typeId: 'pt-4',
    typeName: 'برنامج صباحي',
    presenterId: 'usr-6',
    presenterName: 'ليلى النجار',
    producerId: 'usr-4',
    producerName: 'ريم القحطاني',
    teamMembers: ['ليلى النجار', 'ريم القحطاني'],
    broadcastDays: ['من الأحد إلى الخميس'],
    broadcastTime: '08:30',
    durationMinutes: 40,
    channelName: 'القناة العامة',
    studioName: 'استوديو الصباح البانورامي (C3)',
    status: 'ACTIVE',
    notes: 'طابع حيوي سريع يناسب فترة الصباح الباكر.',
    episodesCount: 215,
    createdAt: '2025-01-20T00:00:00Z',
  },
];

export const INITIAL_EPISODES: Episode[] = [
  {
    id: 'ep-101',
    programId: 'prg-1',
    programName: 'المشهد السياسي',
    seasonNumber: 3,
    episodeNumber: 24,
    title: 'قمة الاستثمار وسلاسل الإمداد: تحولات التحالفات الاقتصادية الإقليمية',
    description: 'حلقة خاصة تناقش مخرجات القمة الاقتصادية المنعقدة اليوم، ودور الطاقة النظيفة ومراكز الذكاء الاصطناعي في إعادة رسم خريطة النفوذ والتنمية.',
    recordingDate: '2026-09-13',
    broadcastDate: '2026-09-13',
    startTime: '21:00',
    endTime: '21:50',
    durationMinutes: 50,
    presenterId: 'usr-5',
    presenterName: 'فيصل العتيبي',
    producerId: 'usr-4',
    producerName: 'ريم القحطاني',
    directorName: 'هاني بن رضوان',
    studioName: 'استوديو الأخبار الرئيسي (A1)',
    introScript: `أهلاً بكم مشاهدينا الكرام إلى حلقة جديدة من "المشهد السياسي".
بينما تشهد العاصمة اليوم انطلاق أضخم قمة اقتصادية للشراكات المستدامة وتوقيع اتفاقيات تقنية سيادية بمليارات الدولارات، نطرح الليلة السؤال الأهم:
كيف تتحول مشروعات الطاقة وسلاسل الإمداد ومراكز الذكاء الاصطناعي إلى أوراق ضغط وتوازن استراتيجي في الساحة الدولية؟
معي في الاستوديو الليلة لمناقشة هذا الملف د. خالد الشمري، وتنضم إلينا من الدوحة الخبيرة نورة الكواري.
ابقوا معنا.`,
    discussionTopics: [
      'تقييم مخرجات القمة الاقتصادية وقوة الاتفاقيات الموقعة.',
      'أهمية الاستثمار السيادي في مراكز البيانات والذكاء الاصطناعي.',
      'تحديات سلاسل الإمداد وتأثيرها على استقرار أسواق الطاقة.',
      'سيناريوهات المرحلة المقبلة والجدول الزمني لتطبيق مشاريع الربط.',
    ],
    directorNotes: 'التبديل إلى الشاشة التفاعلية (Video Wall) عند الدقيقة 12 لعرض خريطة مشروعات الربط الكهربائي.',
    presenterNotes: 'التركيز مع د. خالد حول المقارنة بين اتفاقية اليوم والقمم السابقة، وتوجيه سؤال الذكاء الاصطناعي لنورة الكواري.',
    status: 'READY_FOR_BROADCAST',
    guests: [
      {
        guestId: INITIAL_GUESTS[0].id,
        guestName: INITIAL_GUESTS[0].fullName,
        guestAvatar: INITIAL_GUESTS[0].avatarUrl,
        organization: INITIAL_GUESTS[0].organization,
        jobTitle: INITIAL_GUESTS[0].jobTitle,
        connectionType: 'STUDIO',
        segmentTopic: 'تقييم مخرجات القمة الاقتصادية',
        arrivalStatus: 'ARRIVED',
      },
      {
        guestId: INITIAL_GUESTS[1].id,
        guestName: INITIAL_GUESTS[1].fullName,
        guestAvatar: INITIAL_GUESTS[1].avatarUrl,
        organization: INITIAL_GUESTS[1].organization,
        jobTitle: INITIAL_GUESTS[1].jobTitle,
        connectionType: 'ZOOM_SKYPE',
        segmentTopic: 'الذكاء الاصطناعي وتوطين مراكز البيانات',
        arrivalStatus: 'CONFIRMED',
      },
    ],
    questions: [
      {
        id: 'q-1',
        episodeId: 'ep-101',
        topicName: 'القمة الاقتصادية',
        questionText: 'د. خالد، كيف تقرأ التوقيت السياسي لانعقاد هذه القمة في ظل التوترات الاقتصادية الدولية؟',
        orderIndex: 1,
        assignedToName: 'د. خالد الشمري',
        notes: 'في بداية الحوار مباشرة بعد المقدمة والتقرير.',
        isAsked: false,
      },
      {
        id: 'q-2',
        episodeId: 'ep-101',
        topicName: 'الذكاء الاصطناعي والاستثمار',
        questionText: 'أستاذة نورة، كيف ستنعكس استثمارات الـ 8 مليارات دولار في مراكز البيانات على تنويع الدخل والناتج المحلي؟',
        orderIndex: 2,
        assignedToName: 'نورة الكواري',
        notes: 'استخدام شاشة الغرافيك المصاحبة.',
        isAsked: false,
      },
      {
        id: 'q-3',
        episodeId: 'ep-101',
        topicName: 'سلاسل الإمداد والربط الإقليمي',
        questionText: 'ما هي العقبات التنظيمية أو الجمركية التي قد تعترض الربط الكهربائي والمنصة الرقمية الموحدة؟',
        orderIndex: 3,
        assignedToName: 'الضيفان معاً',
        notes: 'نقاش مفتوح قبل الفاصل الإعلاني.',
        isAsked: false,
      },
    ],
    rundown: [
      {
        id: 'seg-1',
        episodeId: 'ep-101',
        orderIndex: 1,
        title: 'شارة البرنامج ومقدمة المذيع الترحيبية',
        segmentType: 'INTRO',
        startTimeOffset: '00:00:00',
        durationSeconds: 150, // 2m 30s
        endTimeOffset: '00:02:30',
        presenterName: 'فيصل العتيبي',
        scriptText: 'قراءة مقدمة الحلقة من الأوتوكيو (Autocue) مع الموسيقى التصويرية الخافتة.',
        notes: 'كاميرا 1 و 2.',
        isCompleted: false,
      },
      {
        id: 'seg-2',
        episodeId: 'ep-101',
        orderIndex: 2,
        title: 'تقرير تمهيدي: حصاد اليوم الأول للقمة الاقتصادية والاتفاقيات الموقعة',
        segmentType: 'REPORT',
        startTimeOffset: '00:02:30',
        durationSeconds: 240, // 4m 00s
        endTimeOffset: '00:06:30',
        presenterName: 'صوت التقرير: ليلى النجار',
        videoAssetUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        scriptText: 'استعراض بالصوت والصورة لجلسات القمة وكلمات وزراء الاقتصاد ومراسم توقيع الاتفاقيات.',
        newsId: 'nws-1',
        newsTitle: 'انطلاق أعمال القمة الاقتصادية العربية لمناقشة شراكات الاستثمار',
        notes: 'تشغيل الفيديو من سيرفر البث (Playout Server 1).',
        isCompleted: false,
      },
      {
        id: 'seg-3',
        episodeId: 'ep-101',
        orderIndex: 3,
        title: 'المحور الأول: قراءة في الأبعاد الاستراتيجية لمخرجات القمة',
        segmentType: 'LIVE_INTERVIEW',
        startTimeOffset: '00:06:30',
        durationSeconds: 750, // 12m 30s
        endTimeOffset: '00:19:00',
        presenterName: 'فيصل العتيبي',
        guestId: 'gst-1',
        guestName: 'د. خالد بن صالح الشمري',
        scriptText: 'نقاش مباشر في الاستوديو مع الضيف حول التحديات والفرص الاستثمارية.',
        notes: 'كاميرا 3 (كادر مشترك) وكاميرا 1 (كادر المذيع).',
        isCompleted: false,
      },
      {
        id: 'seg-4',
        episodeId: 'ep-101',
        orderIndex: 4,
        title: 'فاصل إعلاني وإخباري موجز',
        segmentType: 'BREAK',
        startTimeOffset: '00:19:00',
        durationSeconds: 180, // 3m 00s
        endTimeOffset: '00:22:00',
        scriptText: 'فاصل تجاري + برومو البرامج القادمة + شريط الأخبار.',
        notes: 'التحويل التلقائي لغرفة التحكم المركزية (MCR).',
        isCompleted: false,
      },
      {
        id: 'seg-5',
        episodeId: 'ep-101',
        orderIndex: 5,
        title: 'المحور الثاني: مراكز بيانات الذكاء الاصطناعي ومستقبل الطاقة المستدامة',
        segmentType: 'LIVE_INTERVIEW',
        startTimeOffset: '00:22:00',
        durationSeconds: 900, // 15m 00s
        endTimeOffset: '00:37:00',
        presenterName: 'فيصل العتيبي',
        guestId: 'gst-2',
        guestName: 'نورة بنت راشد الكواري',
        scriptText: 'مداخلة حية عبر الأقمار الصناعية من الدوحة + مشاركة د. خالد من الاستوديو.',
        newsId: 'nws-2',
        newsTitle: 'عاجل: توقيع اتفاقية استراتيجية لتأسيس أكبر مجمع إقليمي للحوسبة',
        notes: 'شاشة مقسومة (Split Screen) مع رسوم توضيحية جانبية.',
        isCompleted: false,
      },
      {
        id: 'seg-6',
        episodeId: 'ep-101',
        orderIndex: 6,
        title: 'المحور الثالث: سيناريوهات التنفيذ والجدول الزمني للربط المشترك',
        segmentType: 'DISCUSSION',
        startTimeOffset: '00:37:00',
        durationSeconds: 600, // 10m 00s
        endTimeOffset: '00:47:00',
        presenterName: 'فيصل العتيبي',
        guestName: 'الضيفان معاً',
        scriptText: 'الخلاصات الختامية وتوقعات الأداء خلال الربع الرابع من العام.',
        notes: 'تنبيه المذيع عند بقاء 3 دقائق.',
        isCompleted: false,
      },
      {
        id: 'seg-7',
        episodeId: 'ep-101',
        orderIndex: 7,
        title: 'خاتمة الحلقة وشكر الضيوف واستعراض موضوع حلقة الغد',
        segmentType: 'OUTRO',
        startTimeOffset: '00:47:00',
        durationSeconds: 180, // 3m 00s
        endTimeOffset: '00:50:00',
        presenterName: 'فيصل العتيبي',
        scriptText: 'كلمة الوداع، إدراج أسماء فريق العمل، وموسيقى الختام.',
        notes: 'نزول التتر (Credits).',
        isCompleted: false,
      },
    ],
    linkedNewsIds: ['nws-1', 'nws-2'],
    attachments: [],
    createdAt: '2026-09-12T14:00:00Z',
    updatedAt: '2026-09-13T11:00:00Z',
  },
  {
    id: 'ep-102',
    programId: 'prg-2',
    programName: 'عين على الاقتصاد',
    seasonNumber: 2,
    episodeNumber: 45,
    title: 'أسواق الطاقة والذهب: ارتداد المؤشرات وقرارات البنوك المركزية',
    description: 'تحليل أسبوعي لأسعار الفائدة، حركة صناديق الاستثمار السيادية وتحولات موازين التجارة الدولية.',
    recordingDate: '2026-09-14',
    broadcastDate: '2026-09-14',
    startTime: '19:00',
    endTime: '19:45',
    durationMinutes: 45,
    presenterId: 'usr-5',
    presenterName: 'فيصل العتيبي',
    producerId: 'usr-4',
    producerName: 'ريم القحطاني',
    directorName: 'سعود البقمي',
    studioName: 'استوديو الاقتصاد والأسواق (B2)',
    introScript: 'أهلاً بكم إلى جولة اقتصادية شاملة في مسارات المال والأعمال.',
    discussionTopics: ['قرارات الفيدرالي والبنك المركزي الأوروبي', 'أداء خام برنت', 'موجة الذهب القياسية'],
    status: 'PREPARING',
    guests: [INITIAL_GUESTS[1]],
    questions: [],
    rundown: [],
    linkedNewsIds: ['nws-1'],
    attachments: [],
    createdAt: '2026-09-13T09:00:00Z',
    updatedAt: '2026-09-13T09:00:00Z',
  },
];

export const INITIAL_TASKS: EditorialTask[] = [
  {
    id: 'tsk-1',
    title: 'إعداد ومونتاج فيديو تقرير القمة الاقتصادية لحلقة الليلة',
    description: 'تجميع تصريحات وزراء المالية ومقاطع توقيع الاتفاقيات وتسليم المادة الممنتجة بطول 4 دقائق قبل الساعة 18:00.',
    assigneeId: 'usr-7',
    assigneeName: 'عمر الدوسري',
    assigneeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    creatorId: 'usr-4',
    creatorName: 'ريم القحطاني',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    startDate: '2026-09-13T09:00:00Z',
    dueDate: '2026-09-13T18:00:00Z',
    relatedEntityType: 'EPISODE',
    relatedEntityId: 'ep-101',
    relatedEntityTitle: 'حلقة المشهد السياسي (رقم 24)',
    notes: 'التركيز على لقطات توقيع اتفاقية مجمع الحوسبة السحابية.',
    createdAt: '2026-09-13T08:30:00Z',
  },
  {
    id: 'tsk-2',
    title: 'تأكيد الحجز الفضائي والأقمار الصناعية مع استوديو الدوحة',
    description: 'التواصل مع استوديو الدوحة لتأكيد إشارة البث المباشر للضيفة نورة الكواري عند الساعة 21:15.',
    assigneeId: 'usr-4',
    assigneeName: 'ريم القحطاني',
    creatorId: 'usr-4',
    creatorName: 'ريم القحطاني',
    priority: 'HIGH',
    status: 'DONE',
    startDate: '2026-09-13T10:00:00Z',
    dueDate: '2026-09-13T15:00:00Z',
    relatedEntityType: 'EPISODE',
    relatedEntityId: 'ep-101',
    relatedEntityTitle: 'حلقة المشهد السياسي (رقم 24)',
    notes: 'تم فحص جودة الصوت والصورة وتأكيد الخط الاحتياطي.',
    createdAt: '2026-09-13T09:15:00Z',
  },
  {
    id: 'tsk-3',
    title: 'تغطية ميدانية وإجراء مقابلات مع المتحدثين في معرض التقنية الدولي',
    description: 'إجراء لقاءين مسجلين مع ممثلي كبرى الشركات التقنية وتسليم تقرير صحفي للنشرة المسائية.',
    assigneeId: 'usr-6',
    assigneeName: 'ليلى النجار',
    assigneeAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    creatorId: 'usr-2',
    creatorName: 'سارة عبد العزيز',
    priority: 'MEDIUM',
    status: 'TODO',
    startDate: '2026-09-14T08:00:00Z',
    dueDate: '2026-09-14T16:00:00Z',
    relatedEntityType: 'GENERAL',
    relatedEntityTitle: 'تغطية معرض التقنية 2026',
    notes: 'سيتم توفير طاقم تصوير مصاحب.',
    createdAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'tsk-4',
    title: 'تدقيق وتحديث بيانات دراسة المناخ والأمن الغذائي',
    description: 'مراجعة أرقام الانبعاثات في خبر الأستاذ طارق وإعادة إرساله للاعتماد النهائي.',
    assigneeId: 'usr-3',
    assigneeName: 'طارق الهاشمي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    creatorId: 'usr-2',
    creatorName: 'سارة عبد العزيز',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    startDate: '2026-09-13T11:00:00Z',
    dueDate: '2026-09-13T17:00:00Z',
    relatedEntityType: 'NEWS',
    relatedEntityId: 'nws-4',
    relatedEntityTitle: 'تحليل سياسي: توازنات القوى في مفاوضات المناخ',
    createdAt: '2026-09-13T10:30:00Z',
  },
];

export const INITIAL_MEDIA_FILES: MediaFile[] = [
  {
    id: 'med-1',
    fileName: 'arab_economic_summit_keynote.jpg',
    originalName: 'الجلسة الافتتاحية للقمة الاقتصادية 2026.jpg',
    mimeType: 'image/jpeg',
    fileSizeBytes: 2450000, // 2.45 MB
    url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    mediaType: 'IMAGE',
    ownerId: 'usr-7',
    ownerName: 'عمر الدوسري',
    tags: ['قمة اقتصادية', 'مؤتمر', 'وزراء', 'رسمي'],
    description: 'صورة عالية الجودة للقاعة الرئيسية خلال الكلمة الافتتاحية.',
    createdAt: '2026-09-13T08:30:00Z',
  },
  {
    id: 'med-2',
    fileName: 'cloud_ai_datacenter_signing.jpg',
    originalName: 'مراسم توقيع اتفاقية مراكز البيانات.jpg',
    mimeType: 'image/jpeg',
    fileSizeBytes: 3120000,
    url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    mediaType: 'IMAGE',
    ownerId: 'usr-7',
    ownerName: 'عمر الدوسري',
    tags: ['ذكاء اصطناعي', 'سحابية', 'اتفاقية', 'دبي', 'الرياض'],
    description: 'التقاطة رسمية لممثلي الشركات والوزارة عقب التوقيع.',
    createdAt: '2026-09-13T10:10:00Z',
  },
  {
    id: 'med-3',
    fileName: 'metro_station_modern_train.jpg',
    originalName: 'قطار المترو الجديد فائق التطور.jpg',
    mimeType: 'image/jpeg',
    fileSizeBytes: 1890000,
    url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
    mediaType: 'IMAGE',
    ownerId: 'usr-6',
    ownerName: 'ليلى النجار',
    tags: ['مترو', 'نقل', 'محلي', 'بنية تحتية'],
    createdAt: '2026-09-13T10:50:00Z',
  },
  {
    id: 'med-4',
    fileName: 'economic_summit_highlights_package.mp4',
    originalName: 'فيديو حصاد اليوم الأول - القمة الاقتصادية.mp4',
    mimeType: 'video/mp4',
    fileSizeBytes: 48500000, // 48.5 MB
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    mediaType: 'VIDEO',
    ownerId: 'usr-7',
    ownerName: 'عمر الدوسري',
    tags: ['فيديو', 'مونتاج', 'القمة', 'المشهد السياسي'],
    description: 'المادة الممنتجة للبث في الفقرة الثانية من حلقة الليلة.',
    createdAt: '2026-09-13T11:20:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'usr-2',
    title: 'طلب مراجعة تحريرية لخبر عاجل',
    message: 'قام طارق الهاشمي بإرسال خبر "توقيع اتفاقية استراتيجية لتأسيس أكبر مجمع إقليمي للحوسبة" للمراجعة والاعتماد.',
    type: 'NEWS_REVIEW',
    linkUrl: '/news',
    isRead: false,
    createdAt: '2026-09-13T10:10:00Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-7',
    title: 'مهمة إنتاجية جديدة مسندة إليك',
    message: 'أسندت إليك ريم القحطاني مهمة "إعداد ومونتاج فيديو تقرير القمة الاقتصادية لحلقة الليلة".',
    type: 'TASK_ASSIGNED',
    linkUrl: '/tasks',
    isRead: false,
    createdAt: '2026-09-13T09:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'usr-5',
    title: 'تحديث الرانداون: حلقة الليلة جاهزة للبث',
    message: 'اكتمل إعداد جدول تسلسل فقرات حلقة "المشهد السياسي" (رقم 24) وتأكيد الضيوف.',
    type: 'EPISODE_SCHEDULE',
    linkUrl: '/episodes/ep-101',
    isRead: true,
    createdAt: '2026-09-13T11:00:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    userId: 'usr-2',
    userName: 'سارة عبد العزيز',
    userRole: 'EDITOR',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    action: 'نشر خبر',
    entityType: 'NEWS',
    entityId: 'nws-2',
    entityTitle: 'توقيع اتفاقية استراتيجية لتأسيس أكبر مجمع إقليمي للحوسبة السحابية',
    summaryAr: 'قامت مديرة التحرير سارة عبد العزيز باعتماد ونشر الخبر العاجل في شريط الأخبار.',
    timestamp: '2026-09-13T10:15:00Z',
  },
  {
    id: 'act-2',
    userId: 'usr-4',
    userName: 'ريم القحطاني',
    userRole: 'PRODUCER',
    action: 'تحديث جدول الرانداون',
    entityType: 'EPISODE',
    entityId: 'ep-101',
    entityTitle: 'حلقة المشهد السياسي (رقم 24)',
    summaryAr: 'قامت ريم القحطاني بتعديل مدة الفقرة الخامسة وضبط التوقيت الإجمالي للحلقة إلى 50 دقيقة.',
    timestamp: '2026-09-13T11:05:00Z',
  },
  {
    id: 'act-3',
    userId: 'usr-3',
    userName: 'طارق الهاشمي',
    userRole: 'JOURNALIST',
    action: 'إنشاء خبر جديد',
    entityType: 'NEWS',
    entityId: 'nws-1',
    entityTitle: 'انطلاق أعمال القمة الاقتصادية العربية لمناقشة شراكات الاستثمار',
    summaryAr: 'أنشأ الصحفي طارق الهاشمي مسودة الخبر وتدقيق مصادرها الرسمية.',
    timestamp: '2026-09-13T08:15:00Z',
  },
  {
    id: 'act-4',
    userId: 'usr-1',
    userName: 'أحمد المنصوري',
    userRole: 'SUPER_ADMIN',
    action: 'إطلاق خبر عاجل',
    entityType: 'BREAKING_NEWS',
    entityId: 'brk-2',
    entityTitle: 'تحذير الأرصاد من العواصف الرملية',
    summaryAr: 'قام المدير العام أحمد المنصوري بتفعيل شريط التنبيه المناخي العاجل.',
    timestamp: '2026-09-13T11:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-1',
    userName: 'أحمد المنصوري',
    userRole: 'SUPER_ADMIN',
    actionType: 'LOGIN',
    targetEntity: 'AUTH',
    targetId: 'usr-1',
    severity: 'INFO',
    details: 'تسجيل دخول ناجح من عنوان IP موثوق.',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-13T08:00:00Z',
  },
  {
    id: 'aud-2',
    userId: 'usr-2',
    userName: 'سارة عبد العزيز',
    userRole: 'EDITOR',
    actionType: 'PUBLISH',
    targetEntity: 'NEWS',
    targetId: 'nws-2',
    severity: 'WARNING',
    details: 'نشر مباشر لخبر مصنف كعاجل (URGENT) وتجاوز مرحلة الجدولة.',
    ipAddress: '192.168.1.25',
    timestamp: '2026-09-13T10:15:00Z',
  },
  {
    id: 'aud-3',
    userId: 'usr-1',
    userName: 'أحمد المنصوري',
    userRole: 'SUPER_ADMIN',
    actionType: 'ROLE_CHANGE',
    targetEntity: 'USER',
    targetId: 'usr-3',
    severity: 'SECURITY',
    details: 'ترقية صلاحيات المستخدم طارق الهاشمي لإتاحة إضافة مصادر إخبارية جديدة.',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-12T14:30:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  organizationName: 'شبكة الأخبار والإنتاج التلفزيوني الإقليمية',
  organizationNameEn: 'Regional News & Broadcast Network',
  logoUrl: '',
  defaultTimezone: 'Asia/Riyadh (GMT+3)',
  defaultLanguage: 'العربية (Arabic)',
  primaryChannelName: 'القناة الإخبارية الأولى HD',
  autoSaveIntervalSeconds: 30,
  allowGuestProposals: true,
  enableAuditLog: true,
};

export const INITIAL_PROGRAM_EVALUATIONS: ProgramEvaluation[] = [
  {
    id: 'eval-1',
    programId: 'prg-1',
    episodeId: 'ep-101',
    evaluatorId: 'usr-2',
    evaluatorName: 'سارة عبد العزيز',
    evaluatorRole: 'مديرة التحرير وضبط الجودة',
    overallRating: 4.8,
    criteria: {
      editorialQuality: 5,
      timeCommitment: 4,
      guestRelevance: 5,
      visualDirection: 5,
      viewerEngagement: 5,
    },
    strengths: [
      'حوار عميق ومحكم مع ضيوف من الطراز الأول في الاستوديو وعبر الأقمار.',
      'تكامل ممتاز بين التقرير الاستهلالي وجداول الرسوم البيانية التفاعلية.',
      'التزام عالٍ بسياق الموضوع دون انحراف عن الأهداف التحريرية المخططة.',
    ],
    improvements: [
      'تجاوز وقت الفقرة الثانية بـ 45 ثانية تم تداركها في الفقرة الختامية.',
      'إتاحة وقت إضافي لأسئلة المتابعين على منصة X.',
    ],
    notes: 'حلقة نموذجية تبرز القوة التحليلية للبرنامج، التقييم العام ممتاز ويوصى بتكرار هذا القالب في ملفات الطاقة.',
    evaluatedAt: '2026-09-13T22:30:00Z',
  },
  {
    id: 'eval-2',
    programId: 'prg-1',
    evaluatorId: 'usr-1',
    evaluatorName: 'أحمد المنصوري',
    evaluatorRole: 'مدير عام القناة والبرامج',
    overallRating: 4.6,
    criteria: {
      editorialQuality: 5,
      timeCommitment: 5,
      guestRelevance: 4,
      visualDirection: 5,
      viewerEngagement: 4,
    },
    strengths: [
      'حضور ذهني وسرعة بديهة استثنائية لمقدم البرنامج في إدارة وتوجيه الحوار.',
      'استخدام مبتكر لشاشات العرض التفاعلية (Video Wall) في الاستوديو A1.',
      'تنسيق مسبق ممتاز أتاح بث تصريحات حصرية قبل الوكالات المنافسة.',
    ],
    improvements: [
      'الحاجة لموازنة التمثيل الجغرافي بين المحللين في الملفات الإقليمية.',
    ],
    notes: 'البرنامج يحافظ على مكانته كأحد البرامج الحوارية الأكثر تأثيراً في خريطة البث.',
    evaluatedAt: '2026-09-10T14:00:00Z',
  },
  {
    id: 'eval-3',
    programId: 'prg-2',
    evaluatorId: 'usr-2',
    evaluatorName: 'سارة عبد العزيز',
    evaluatorRole: 'مديرة التحرير وضبط الجودة',
    overallRating: 4.4,
    criteria: {
      editorialQuality: 5,
      timeCommitment: 4,
      guestRelevance: 4,
      visualDirection: 4,
      viewerEngagement: 5,
    },
    strengths: [
      'تبسيط رائع للمصطلحات الاقتصادية المعقدة لجمهور المشاهدين العاديين.',
      'سرعة مواكبة إغلاقات الأسواق مع بث بيانات البورصة اللحظية.',
    ],
    improvements: [
      'ضرورة توفير مقتطفات فيديو قصيرة (Reels/Shorts) للنشر الرقمي المتزامن.',
    ],
    notes: 'برنامج متميز ذو وتيرة حيوية ويحقق ريتنج عالي في فئة رجال الأعمال ورواد الأعمال.',
    evaluatedAt: '2026-09-11T18:00:00Z',
  },
];

