import { test, expect } from '@playwright/test';
import { openNav, signIn } from './helpers';
test.use({ actionTimeout: 15_000 });

test('team creates, reviews, prepares, approves and airs a bulletin story', async ({ browser }) => {
  test.setTimeout(180_000);
  const writer = await signIn(browser, 'journalist@akhbar.tv');
  const editor = await signIn(browser, 'editor@akhbar.tv');
  const manager = await signIn(browser, 'producer@akhbar.tv');
  const control = await signIn(browser, 'director@akhbar.tv');
  const headline = `رحلة فريق التحرير ${Date.now()}`;
  const text = 'أكد المسؤولون اكتمال الاستعدادات لتشغيل المشروع الجديد بعد مراجعة البيانات والتنسيق مع الجهات المعنية، ويواصل فريق التحرير متابعة المستجدات والتحقق من التفاصيل قبل النشر.';
  let newsId = '';
  let bulletinId = '';
  const data = async (page: typeof writer.page) => (await page.request.get('/api/v1/data')).json();
  const leave = async (page: typeof writer.page) => openNav(page, 'الرئيسية');
  const transition = async (page: typeof writer.page, name: string) => {
    await page.getByRole('button', { name, exact: true }).first().click();
    await page.getByRole('button', { name: 'تأكيد ونقل الحالة', exact: true }).click();
    await expect(page.getByRole('button', { name: 'تأكيد ونقل الحالة', exact: true })).not.toBeVisible();
  };
  try {
    await writer.page.goto('/news/new');
    await writer.page.locator('#news-headline-input').fill(headline);
    await writer.page.locator('#news-short-title-input').fill(headline);
    await writer.page.locator('#news-summary-textarea').fill(text);
    await writer.page.locator('[contenteditable="true"]').first().fill(text);
    await writer.page.getByRole('button', { name: 'حفظ كمسودة', exact: true }).click();
    await expect.poll(async () => (await data(writer.page)).collections.news.find((r: any) => r.d.title === headline)?.id).toBeTruthy();
    newsId = (await data(writer.page)).collections.news.find((r: any) => r.d.title === headline).id;
    await transition(writer.page, 'إرسال للمراجعة والتدقيق');
    await leave(writer.page);

    await editor.page.goto(`/news/${newsId}`);
    const reviews = editor.page.getByRole('region', { name: 'ملاحظات مراجعة النص' });
    await reviews.getByText('إضافة ملاحظة على مقتطف', { exact: true }).click();
    await reviews.getByLabel('مقتطف من النص', { exact: true }).fill('اكتمال الاستعدادات');
    await reviews.getByLabel('ملاحظة المراجعة', { exact: true }).fill('حدد مصدر التحقق من الاستعدادات');
    await reviews.getByRole('button', { name: 'إضافة الملاحظة', exact: true }).click();
    await expect(reviews.getByText('حدد مصدر التحقق من الاستعدادات', { exact: true })).toBeVisible();
    await editor.page.getByRole('button', { name: 'إعادة للكاتب مع ملاحظات', exact: true }).click();
    await editor.page.locator('#status-transition-comment').fill('استكمل توثيق المصدر');
    await editor.page.getByRole('button', { name: 'تأكيد ونقل الحالة', exact: true }).click();
    await leave(editor.page);
    await writer.page.goto(`/news/${newsId}`);
    const writerReviews = writer.page.getByRole('region', { name: 'ملاحظات مراجعة النص' });
    await writerReviews.getByRole('textbox', { name: /رد على مراجعة/ }).fill('تم التحقق من البيان الرسمي');
    await writerReviews.getByRole('button', { name: 'إرسال الرد', exact: true }).click();
    await expect(writerReviews.getByText('تم التحقق من البيان الرسمي', { exact: true })).toBeVisible();
    await writer.page.locator('[contenteditable="true"]').first().fill(`${text} المصدر: البيان الرسمي المنشور.`);
    await transition(writer.page, 'إرسال للمراجعة والتدقيق');
    await leave(writer.page);
    await editor.page.goto(`/news/${newsId}`);
    await editor.page.getByRole('button', { name: 'تمت معالجة الملاحظة', exact: true }).click();
    await transition(editor.page, 'اعتماد الخبر للنشر');
    await leave(editor.page);

    await openNav(manager.page, 'النشرات');
    await manager.page.getByRole('button', { name: 'نشرة جديدة', exact: true }).click();
    const form = manager.page.locator('#form-page-root');
    await form.getByRole('radio', { name: /فارغة/ }).click();
    await form.getByLabel('عنوان النشرة', { exact: true }).fill(headline);
    const editorId = (await (await editor.page.request.get('/api/v1/auth/me')).json()).user.id;
    await form.locator('#bulletin-editor').selectOption(editorId);
    await form.getByRole('button', { name: 'إنشاء وفتح الرانداون', exact: true }).click();
    await expect(manager.page.getByTestId('bulletin-rundown')).toBeVisible();
    await expect.poll(async () => (await data(manager.page)).collections.bulletins.find((r: any) => r.d.title === headline)?.id).toBeTruthy();
    bulletinId = (await data(manager.page)).collections.bulletins.find((r: any) => r.d.title === headline).id;
    await manager.page.getByRole('button', { name: 'بيانات النشرة', exact: true }).click();
    await manager.page.locator('#form-page-root').getByRole('button', { name: 'محرر النشرة ثم مدير التحرير', exact: true }).click();
    await manager.page.locator('#form-page-root').getByRole('button', { name: 'حفظ', exact: true }).click();
    await manager.page.getByRole('button', { name: 'من غرفة الأخبار', exact: true }).click();
    await manager.page.locator('#form-page-root').getByRole('checkbox', { name: new RegExp(headline) }).check();
    await manager.page.locator('#form-page-root').getByRole('button', { name: /إضافة.*للنشرة/ }).click();
    await expect(manager.page.getByText('أُضيفت 1 قصة كمسودات في آخر النشرة', { exact: true })).toBeVisible();
    await manager.page.getByRole('button', { name: 'تكليف إعداد النشرة', exact: true }).click();
    const taskForm = manager.page.locator('#form-page-root');
    await taskForm.getByLabel('عنوان التكليف', { exact: true }).fill('تدقيق تجهيز القصة');
    await taskForm.getByLabel('المسؤول عن التكليف', { exact: true }).selectOption(editorId);
    await taskForm.getByLabel('موعد التسليم', { exact: true }).fill(`${new Date().toISOString().slice(0, 10)}T23:00`);
    await taskForm.getByRole('button', { name: 'حفظ التكليف', exact: true }).click();
    await expect(manager.page.getByText('حُفظ التكليف وأُرسل للمسؤول', { exact: true })).toBeVisible();
    await manager.page.getByRole('button', { name: `فتح ${headline}`, exact: true }).click();
    await manager.page.getByTestId('story-editor').getByRole('button', { name: 'حفظ وإرسال للاعتماد', exact: true }).click();
    await expect(manager.page.getByTestId('story-editor')).not.toBeVisible();
    await expect.poll(async () => (await data(manager.page)).collections.bulletinStories.filter((r: any) => r.d.bulletinId === bulletinId && r.d.slug === headline).map((r: any) => ({ id: r.id, status: r.d.status }))).toEqual([expect.objectContaining({ status: 'READY' })]);
    await leave(manager.page);

    await editor.page.goto(`/bulletins/${bulletinId}`);
    await editor.page.getByRole('button', { name: `فتح ${headline}`, exact: true }).click();
    await editor.page.getByTestId('story-editor').getByRole('button', { name: /اعتمادي|حفظ واعتماد للهواء/ }).click();
    await expect(editor.page.getByTestId('story-editor')).not.toBeVisible();
    await openNav(editor.page, 'المهام');
    await editor.page.getByRole('button', { name: 'تعديل المهمة: تدقيق تجهيز القصة', exact: true }).first().click();
    await editor.page.locator('#task-status-select').selectOption('COMPLETED');
    await editor.page.getByRole('button', { name: 'حفظ المهمة', exact: true }).click();
    await expect.poll(async () => (await data(editor.page)).collections.tasks.find((r: any) => r.d.relatedEntityId === bulletinId)?.d.status).toBe('COMPLETED');
    await leave(editor.page);
    await control.page.goto(`/bulletins/${bulletinId}`);
    await control.page.getByRole('button', { name: `فتح ${headline}`, exact: true }).click();
    await control.page.getByTestId('story-editor').getByRole('button', { name: /اعتمادي|حفظ واعتماد للهواء/ }).click();
    await expect(control.page.getByTestId('story-editor')).not.toBeVisible();
    await expect.poll(async () => (await data(control.page)).collections.bulletinStories.find((r: any) => r.d.bulletinId === bulletinId && r.d.slug === headline)?.d.status).toBe('APPROVED');
    await openNav(control.page, 'وضع الهواء');
    await control.page.getByLabel('الحلقة أو النشرة', { exact: true }).selectOption(bulletinId);
    await control.page.getByRole('button', { name: 'بدء البث', exact: true }).click();
    if (await control.page.getByRole('alertdialog').isVisible()) await control.page.getByRole('alertdialog').getByRole('button', { name: 'تأكيد', exact: true }).click();
    await expect.poll(async () => (await data(control.page)).collections.onAir.find((r: any) => r.id === bulletinId)?.d.status).toBe('LIVE');
    await control.page.getByRole('button', { name: 'إنهاء البث', exact: true }).click();
    await control.page.getByRole('alertdialog').getByRole('button', { name: 'تأكيد', exact: true }).click();
    await expect.poll(async () => (await data(control.page)).collections.onAir.find((r: any) => r.id === bulletinId)?.d.status).toBe('ENDED');
    await expect.poll(async () => (await data(control.page)).collections.onAir.find((r: any) => r.id === bulletinId)?.d.log.length).toBeGreaterThan(0);
    const aired = (await data(control.page)).collections.onAir.find((r: any) => r.id === bulletinId).d;
    expect(aired.status).toBe('ENDED');
    expect(aired.log[0].endedAt).toBeTruthy();
    expect([...writer.errors, ...editor.errors, ...manager.errors, ...control.errors]).toEqual([]);
  } finally {
    await writer.close(); await editor.close(); await manager.close(); await control.close();
  }
});
